### ISSUE TITLE
Thunderbolt4 Support is more important than you might think. 

### ISSUE THREAD

**Issue by fschlegelone** [AsahiLinux/docs#104]
As really nobody is working with his macbook on the laps, it's just a main reason not to use asahi right now :( 
Me (and I assume many other guys out here) Are having its mac connected to a TB4 Dokingstation with 2 or more Displays, and everything you need. 
So without TB4 support it's not that much better than running a Container/VM (for me personally, dont use my opinion as a general fact please.) 

Do you plan on implementing it soon, or is it harder than I think?

**Comment by rowanG077** [comment]
What gives it the impression that it's not seen as important? USB and Thunderbolt are very complex protocols. A ton of work has already been done but it's not ready yet.

**Comment by fschlegelone** [comment]
@rowanG077 Because it's the only feature that is not supported yet :D 
Just wanted to mention it. If it's already seens as important and constantly worked on - allgood.

**Comment by louwers** [comment]
https://github.com/AsahiLinux/docs/wiki/%22When-will-Asahi-Linux-be-done%3F%22

**Comment by fschlegelone** [comment]
@louwers I actually agree with that. My bad.

**Comment by fschlegelone** [comment]
case closed

**Comment by abjugard** [comment]
Not disagreeing with the point about ETAs, but just wanted to chime in that not having Thunderbolt support is the reason I am not running Asahi Linux.
