### ISSUE TITLE
After installation I cannot boot with `option`

### ISSUE THREAD

**Issue by hooke007** [AsahiLinux/docs#107]
I cannot choose which disk to start.

**Comment by chadmed** [comment]
You hold the power button to pick a boot disk on Apple Silicon Macs, not Option. iBoot does not understand anything other than the power button.

**Comment by hooke007** [comment]
But how could i did to enter into the recovery mode.

**Comment by chadmed** [comment]
Select the 'Options' option on the boot menu.

If this is your firs time booting after running the installer, you just select the Asahi boot option. This is all told to you in the installer before you reboot. Read the instructions.

**Comment by hooke007** [comment]
No. After several months with Asahi, I cannot remember anything in the installer's instructions.
