### ISSUE TITLE
Validate kernel & installer on all machines

### ISSUE THREAD

**Issue by marcan** [AsahiLinux/docs#11]
- [ ] J274
- [ ] J293
- [ ] J313
- [ ] J314
- [ ] J316
- [ ] J456
- [ ] J457

**Comment by aaron-trout** [comment]
I installed on J314 (14" M1 Max) this morning by running `curl -L https://alx.sh/dev | sh`. Aside from having to clear out some APFS snapshots (TimeMachine) to help with MacOS partition shrinking, no issues at all!

```
$ uname -a
Linux aaron-asahi 5.17.0-rc7-asahi-next-20220310-2-1-ARCH #6 SMP PREEMPT Thu, 17 Mar 2022 15:37:05 +0000 aarch64 GNU/Linux
```

**Comment by jannau** [comment]
installation of Asahi Linux Desktop into free space on j457 worked

**Comment by gjsman** [comment]
Successful install from recoveryOS onto FileVault-enabled MacBook Air M1 with 7 core GPU 16GB RAM A2337 here.

**Comment by marcan** [comment]
iMac has been tested and I just fixed the 4T+ issue, so I think we can tentatively say this is done. Thanks everyone!
