### ISSUE TITLE
Error During Asahi Linux Installation - "No Internet Connection" at Setting Asahi as Default Boot Volume Step

### ISSUE THREAD

**Issue by keylium** [AsahiLinux/docs#122]
## Description
I am attempting to install Asahi Linux. However, I encounter an error message at the step "Setting the new OS as the default boot volume..." indicating that there is no internet connection.

```
Setting the new OS as the default boot volume...
Bootability failed Error Domain=BYErrorDomain Code=102 "Can’t continue because you are not connected to the Internet" UserInfo={NSUnderlyingError=0x600002a50240 {Error Domain=AuthInstallErrorDomain Code=11 "(null)"}, BYErrorHint=NetworkRequired, BYPersonalizationType=os, NSLocalizedDescription=Can’t continue because you are not connected to the Internet}
Failed to run bless. Press enter to try again.
```

## Expected Behavior
The installation process should proceed without any errors as I am certain that my device is connected to the internet.

## Actual Behavior
An error message stating "no internet connection" appears, halting the installation process.

## Additional Information
My internet connection was briefly in a restricted mode, but it has been released from restricted mode since the date changed.

<details><summary>Log of the installation process</summary>
<p>
Enter a name for your OS
» OS name (Fedora Linux with KDE Plasma): Asahi

Using macOS 13.5 for OS firmware

Downloading macOS OS package info...

Creating new stub macOS named Asahi
Installing stub macOS into disk0s5 (Asahi)
Preparing target volumes...
Checking volumes...
Beginning stub OS install...

Setting up System volume...
 100.00% (0.00 B/s)
Setting up Data volume...
Setting up Preboot volume...
 100.00% (0.00 B/s))
Setting up Recovery volume...
 100.00% (4.29 MB/s)
Wrapping up...

Stub OS installation complete.

Adding partition EFI (524.29 MB)...
  Formatting as FAT...
Adding partition Boot (1.07 GB)...
Adding partition Root (191.16 GB)...
Collecting firmware...
  100.00% Installing OS...
 100.00% (0.00 B/s)
  Copying from esp into disk0s4 partition...
 100.00% (0.00 B/s)
  Copying firmware into disk0s4 partition...
  Extracting boot.img into disk0s7 partition...
 100.00% (5.46 MB/s)
  Extracting root.img into disk0s6 partition...
  29.48% (3.26 MB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 2988441600-2996830207
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  29.60% (2.38 MB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 2996830208-3013607423
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  29.72% (1.55 MB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 3013607424-3026190335
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  29.84% (1.23 MB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 3026190336-3035627519
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  29.96% (1.07 MB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 3035627520-3046113279
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  30.07% (933.42 KB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 3046113280-3058696191
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  30.19% (809.99 KB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 3058696192-3073376255
Error downloading data (Remote end closed connection without response), retrying... (1/10)
  30.31% (703.14 KB/s)root        : ERROR    Request failed for https://asahilinux-fedora.b-cdn.net/os/fedora-40-kde-202405221600.zip range 3073376256-3090153471
Error downloading data (Remote end closed connection without response), retrying... (1/10)
 100.00% (895.59 KB/s)
Downloading extra files...
  Downloading mozilla-openh264-2.4.1-2.fc40.aarch64.rpm (1/2)...

  Downloading openh264-2.4.1-2.fc40.aarch64.rpm (2/2)...

Preparing to finish installation...
Collecting installer data...

To continue the installation, you will need to enter your macOS
admin credentials.

Password for {username}:

Setting the new OS as the default boot volume...
Bootability failed Error Domain=BYErrorDomain Code=102 "Can’t continue because you are not connected to the Internet" UserInfo={NSUnderlyingError=0x600002a50240 {Error Domain=AuthInstallErrorDomain Code=11 "(null)"}, BYErrorHint=NetworkRequired, BYPersonalizationType=os, NSLocalizedDescription=Can’t continue because you are not connected to the Internet}
Failed to run bless. Press enter to try again.

To continue the installation, you will need to enter your macOS
admin credentials.

Password for {username}:

Setting the new OS as the default boot volume...
Bootability failed Error Domain=BYErrorDomain Code=102 "Can’t continue because you are not connected to the Internet" UserInfo={NSUnderlyingError=0x600000c44060 {Error Domain=AuthInstallErrorDomain Code=11 "(null)"}, BYErrorHint=NetworkRequired, BYPersonalizationType=os, NSLocalizedDescription=Can’t continue because you are not connected to the Internet}
Failed to run bless. Press enter to try again.
</p>
</details> 

---
Please let me know if additional details are needed.

**Comment by marcan** [comment]
This is an Apple tool (bless) talking to Apple servers (tatsu). Sorry, we have zero debuggability or discoverability here. Presumably something about your setup or network is blocking these requests. A macOS update or install would have the same issue; if you can reproduce it that way, please file a Feedback report with Apple so they can look into it.

If you run the Asahi Linux install from recoveryOS instead of macOS, this particular step will be skipped (and this is the supported way of not having any phone-home steps during the install, we can't avoid it if you run from macOS).

**Comment by keylium** [comment]
I had Apple-related domains in the NextDNS deny list, so I turned them off and was able to proceed!
Thank you!

![ScreenShot 2024-06-02 19 42 03](https://github.com/AsahiLinux/docs/assets/63142283/03f3235d-5996-40f3-ba86-69dfd0ba3616)
