### ISSUE TITLE
Running Asahi under Orka

### ISSUE THREAD

**Issue by kamal-shaker** [AsahiLinux/docs#138]
Hi, I'd like to test out Asahi on my Mac, has anyone tried running in under Orka Desktop? (https://github.com/macstadium/orka-desktop)

What happens when I run `curl https://alx.sh | sh` within a VM started under Orka (or other VM managers).

Kamal.

**Comment by DavidBuchanan314** [comment]
Asahi exists to provide support for apple-silicon hardware, so it doesn't make much sense to run it in a VM, and if you managed to do that you wouldn't be testing much of the "asahi" parts.

If you'd like to test out Fedora, you can create a VM using their regular arm64 install image.

> What happens when I run `curl https://alx.sh | sh` within a VM

Presumably, an error message (although I am slightly curious, it wouldn't hurt to try)

**Comment by kamal-shaker** [comment]
Ahh, OK, Orka isn't a full virtualisation anyway, it's designed for testing MacOS specifically AFIAK.

Tried anyway:

```
The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer will guide you through the process of setting up
Asahi Linux on your Mac.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


Collecting system information...
  Product name: Apple Virtual Machine 1
  SoC: Apple M3 Max (Virtual)
  Device class: vma2macosap
  Product type: VirtualMac2,1
  Board ID: 0x20
  Chip ID: 0xfe00
  System firmware: iBoot-10151.140.19
  Boot UUID: 1E7C510E-9374-407E-8797-683A5C73371D
  Boot VGID: 1E7C510E-9374-407E-8797-683A5C73371D
  Default boot VGID: 1E7C510E-9374-407E-8797-683A5C73371D
  Boot mode: macOS (overriden)
  OS version: 14.6 (23G80)
  OS restore version: 23.7.80.0.0,0
  Main firmware version: 14.6 (23G80)
  No Fallback System Firmware / rOS
  SFR version: 23.7.80.0.0,0
  SystemRecovery version: 23.7.80.0.0,0 (14.6 23G80)
  Login user: test

This device is not supported yet!
Please check out the Asahi Linux Blog for updates on device support:

   https://asahilinux.org/blog/


```

Oh well. 🤷

I'll install some full virtualisation software and try Fedora.
