### ISSUE TITLE
About Virtual Machines

### ISSUE THREAD

**Issue by loadcorp** [AsahiLinux/docs#21]
Is it possible to use QEMU (in this case manager - https://virt-manager.org/)? I mean create virtual machines from the Host - which is Arch Linux on Apple M1.

**Comment by jannau** [comment]
qemu with kvm works well out of the box on M1 Pro/Max/Ultra. On the original M1 it needs an unreleased qemu version to work well out of the box. It work afaik with `higmem=off`. No idea if /how that works out of the box with virt-manager.

**Comment by loadcorp** [comment]
> qemu with kvm works well out of the box on M1 Pro/Max/Ultra

You mean it is work from MacOS not from Asahi Linux?

**Comment by jannau** [comment]
no, it works in Asahi Linux. On the original M1 it will be easier to setup with the soon to be released qemu 7.0.

**Comment by loadcorp** [comment]
Thanks for the clarification :)

**Comment by wkozaczuk** [comment]
I have just found this issue while I was looking to see if I can use AsahiLinux as a more powerful platform for my virtualization development activities. According to this, I should be able to buy MacMini M1 (2020), install AsahiLinux on it, and run QEMU 7.0 with KVM on, right? Will I need to do anything special to enable KVM? 

On a side note, I would imagine MacMini M1 is way more powerful than Odroid N2+ (https://www.hardkernel.com/shop/odroid-n2-with-4gbyte-ram-2/), no?

**Comment by wintifrosch** [comment]
@jannau: To install on a MacMini M1, `sudo pacman -S qemu-system-aarch64` should work? 
As it seems, there is currently a dependency error with `edk2-armvirt` , as posted in the [ArchLinux Forum](https://archlinuxarm.org/forum/viewtopic.php?f=9&t=16029) and in [ArchLinux Bug Reports](https://bugs.archlinux.org/task/74773).
Do you have any tips for me how to proceed?

**Comment by jannau** [comment]
@wintifrosch , I don't see `qemu-system-aarch64` in arch linux arm's package repo. I only have `extra/qemu` and `extra/qemu-headless` and I have the second one installed.

**Comment by wintifrosch** [comment]
@jannau I receive several non-resolvable dependencies for qemu-headless: 
```
$ sudo pacman -S qemu-headless
resolving dependencies...
warning: cannot resolve "edk2-ovmf", a dependency of "qemu-system-x86"
warning: cannot resolve "seabios", a dependency of "qemu-system-x86"
warning: cannot resolve "qemu-system-x86", a dependency of "qemu-base"
:: The following package cannot be upgraded due to unresolvable dependencies:
      qemu-base

:: Do you want to skip the above package for this upgrade? [y/N] 

```

With the new QEMU Release 7, the package setup changed ([ArchLinux News posted 2022-05-09 by David Runge](https://archlinux.org/news/qemu-700-changes-split-package-setup/)).

> With the update to qemu 7.0.0 the package has been turned into a more fine grained split package utilizing meta packages.
> The qemu package is now virtually provided by the meta packages qemu-base, qemu-desktop and qemu-full.
> • The functionality of qemu prior to 7.0.0 is replaced by qemu-desktop
> • The functionality of qemu-headless is replaced by qemu-base

I receive the same three errors after `sudo pacman -S qemu-base` (edk2-ovmf, seabios, qemu-system-x86).

As it seems, QEMU was adapted for ALARM, since there's a folder on github [archlinuxarm/PKGBUILDs/extra/QEMU](https://github.com/archlinuxarm/PKGBUILDs/tree/master/extra/qemu), but I don't know how to use the files published there.
_______________________________ 
My `pacman.conf` shows the following entries: 
```
[options]
HoldPkg     = pacman glibc
Architecture = aarch64
CheckSpace

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[asahi]
Include = /etc/pacman.d/mirrorlist.asahi

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[alarm]
Include = /etc/pacman.d/mirrorlist

[aur]
Include = /etc/pacman.d/mirrorlist
```

**Comment by jannau** [comment]
My bad, I was in a hurry and didn't want to update. Reproduced with the restructured qemu 7.0 package. The qemu update in https://github.com/archlinuxarm/PKGBUILDs/commit/dff79d99f0a0d6f05447c1f8ada166da00f6ed8b missed to add the additional dependencies.

**Comment by zanfix** [comment]
Hi there,

Well I am still unable to run a vm with kvm...

What i tried:

- using alarm package from repo (v7): I get "Synchronous Exception" (see https://gitlab.com/qemu-project/qemu/-/issues/1002)
- tried  to revert the commit as mentioned into the link above and recompile the package (same problem)
- tried compiling version 6.2 from source and running it with with `-highmem=off`. and I get: `qemu-system-aarch64: -accel kvm: -m and ,maxmem option values require an IPA range (40 bits) larger than the one supported by the host (36 bits)`,  even with 512megs of ram (if it even matters)

Am I doing something wrong?

**Comment by marcan** [comment]
As that issue explains, the problem is that KVM cannot handle heterogeneous CPUs like the performance/efficiency cores in M1 machines (this used to sort of work but was never correct). You need to use `taskset` to restrict qemu to either the efficiency cores or the performance cores. Otherwise things will go wrong as the virtual CPUs migrate around different physical CPUs.

**Comment by zanfix** [comment]
I think that the problem is something else, efi related.
Anyway, about taskset, i tried making a cpuset cgroup and running the vm inside of it and it did not make any difference

**Comment by boris-kolpackov** [comment]
> You need to use taskset to restrict qemu to either the efficiency cores or the performance cores.

For those looking at `/proc/cpuinfo` and wondering which ones are efficiency cores and which -- performance, at lest on M1 it appears 0-3 are E and 4-7 are P. This can be inferred by correlating the `lscpu` and `lscpu -e` output.

@marcan Can we assume that this order is reasonably stable and won't change, for example, after a kernel upgrade?

**Comment by jannau** [comment]
yes, the order matches how CPU cores are layout in hardware

**Comment by boris-kolpackov** [comment]
> yes, the order matches how CPU cores are layout in hardware

This is the output I get on M1 from `lscpu -e`:

```
CPU NODE SOCKET CORE ONLINE    MAXMHZ   MINMHZ       MHZ
  0    0      0    0    yes 2064.0000 600.0000  600.0000
  1    0      0    1    yes 2064.0000 600.0000  600.0000
  2    0      0    2    yes 2064.0000 600.0000  600.0000
  3    0      0    3    yes 2064.0000 600.0000  600.0000
  4    0      0    0    yes 2988.0000 600.0000 1956.0000
  5    0      0    1    yes 2988.0000 600.0000 1956.0000
  6    0      0    2    yes 2988.0000 600.0000 1956.0000
  7    0      0    3    yes 2988.0000 600.0000 1956.0000
```

I am fuzzy on the exact meaning, but the `CORE` column suggests that this might not be the case.

**Comment by sheerun** [comment]
Anyone was able to install qemu? I have the same errors as @wintifrosch

**Comment by np22-jpg** [comment]
> Anyone was able to install qemu? I have the same errors as @wintifrosch

I was able to get qemu working by downloading each individual file from a [mirror](https://geo.mirror.pkgbuild.com/extra/os/x86_64/) (note that even though this is an x86 mirror, the packages are "any"), then using 
`pacman -U /path/to/<package>-any.pkg.tar.zst` for each individual package, as per [this](https://archlinuxarm.org/forum/viewtopic.php?f=15&t=16037) forum post.

**Comment by sheerun** [comment]
@np22-jpg You mean every package or some specific ones? Isn't it unsecure to mass-install packages?

**Comment by xet7** [comment]
I added to Ubuntu Asahi section of wiki https://github.com/AsahiLinux/docs/wiki/SW:Alternative-Distros links how did I build and install at Ubuntu 22.10 Asahi these:

- [Qemu and virt-manager, Qemu running ReactOS 32bit nightly with networking](https://github.com/AsahiLinux/docs/wiki/SW%3AUbuntu-Asahi-Qemu)
- [Gambas](https://github.com/AsahiLinux/docs/wiki/SW%3AUbuntu-Asahi-Gambas)
- [Godot](https://github.com/AsahiLinux/docs/wiki/SW%3AUbuntu-Asahi-Godot)
