### ISSUE TITLE
It says "Alert login" when I boot the OS and can't login.

### ISSUE THREAD

**Issue by raise104** [AsahiLinux/docs#23]
What is the login ID and password for alert login?
I put admin ID and password but it was incorrect.

**Comment by jannau** [comment]
Did you install Asahi Linux minimal or Asahi Linux desktop image? The desktop installation creates an user account + password during first boot.
Is `alert` (double) translated `alarm`? That looks like the minimal installation then. Credentials are listed in [Asahi minimal section](https://asahilinux.org/2022/03/asahi-linux-alpha-release/#asahi-linux-minimal-arch-linux-arml) of the  the release announcement.

**Comment by raise104** [comment]
once I selected Asahi Linux desktop and it worked well! thanks XD
