### ISSUE TITLE
Is it theoretically possible to run Windows ARM?

### ISSUE THREAD

**Issue by ovalny** [AsahiLinux/docs#24]
Is it theoretically possible to run Windows ARM with m1n1 + U-Boot on Apple Silicon?

If so, why hasn't anyone started doing this?

**Comment by jannau** [comment]
On a very high level it's of course theoretically possible. It's however piratically impossible for anyone except Microsoft. It would require very low-level changes to Windows only Microsoft is able to do (at least driver for apple's interrupt controller). Also AFAIK Windows requires ACPI, which is not provided by u-boot.

**Comment by marcan** [comment]
Correct. It is not legally possible without Microsoft's help, without using a VM. You can already run Windows ARM on Asahi Linux in a VM.
