### ISSUE TITLE
Progress documentation for the not-so technically inclided followers and backers?

### ISSUE THREAD

**Issue by mbrennwa** [AsahiLinux/docs#3]
Asahi Linux is interesting to many people, but most will not understand the technical details of the work needed to bring proper Linux support to the M1 Macs.

To attract more attention, support and sponsoring for the project from such parties, it would be useful to provide regular progress reports that are comprehensible to non-specialists. Take me as an example: I am a Asahi Linux sponsor because a I want proper Linux support on the M1 Macs. However, I don't really understand the process, and I am not sure I am sponsoring the right thing.

For example, weekly updates on the Asahi Linux website with a few lines highlighting the most relevant progress and how this is relevant in the big picture of getting proper Linux Support for M1 Macs would be great!

**Comment by marcan** [comment]
I actually plan to do monthly progress reports, but ended up late on the January one as there is too much stuff going on, so the first one will be a combined January-Feburary report :-)

**Comment by marcan** [comment]
The first progress report is out, second one is coming soon :)

**Comment by kasperk81** [comment]
> The first progress report is out, second one is coming soon :)

Hi, where was this progress report published? Tasks: https://github.com/AsahiLinux/docs/wiki/Tasks were updated in Feb, and https://github.com/AsahiLinux/docs/wiki/Project-status was update in Jan. I couldn't find the info on your website https://asahilinux.org either.

(in particular, I am looking for Wi-Fi status)

**Comment by rrbutani** [comment]
@kasperk81 It's on the [blog](https://asahilinux.org/blog/) on asahilinux.org: [here](https://asahilinux.org/2021/03/progress-report-january-february-2021/).

**Comment by kasperk81** [comment]
ok, i was looking for something from April when the comment was posted.

**Comment by mbrennwa** [comment]
> The first progress report is out, second one is coming soon :)

How about investing a bit of time for an update to the February report? How are things coming along?
