### ISSUE TITLE
Segmentation fault on Visual Studio Code

### ISSUE THREAD

**Issue by h0m3** [AsahiLinux/docs#30]
Hello Friends,

I've added a [bugreport](https://github.com/microsoft/vscode/issues/153849) on the vscode page due to a segmentation fault by launching the Visual Studio Code editor. Since it does rely on Electron its probably related to the lack of 16K page support that also affects Chromium in order to [apply the same fix](https://chromium.googlesource.com/chromium/src/+/a704c3a94179e6f3abb28f090d096ced72657d7c) if possible.

The issue can be tracked at https://github.com/microsoft/vscode/issues/153849

**Comment by domschl** [comment]
It's fixed in latest Insiders build of VSCode:

https://aur.archlinux.org/packages/visual-studio-code-insiders-bin

**Comment by marcan** [comment]
Closing since this should be fixed.

**Comment by h0m3** [comment]
Confirmed,

The issue is fixed. Sorry for the delayed response.
