### ISSUE TITLE
NVRAM support not documented in the wiki

### ISSUE THREAD

**Issue by asdfugil** [AsahiLinux/docs#31]
There is no mention of NVRAM in the [Feature Support](https://github.com/AsahiLinux/docs/wiki/Feature-Support) page.

Also, is there any technical reason why the nvram cannot be used as the efi variable store besides "read/writing from it is not supported yet"?

**Comment by marcan** [comment]
I don't think it's appropriate to throw random EFI variables in the (very much unrelated to EFI and limited size) system nvram, plus it does not cleanly work with the per-OS container concept we have. I don't think this a the direction we want to go in.
