### ISSUE TITLE
macOS Ventura Compatibility?

### ISSUE THREAD

**Issue by Mase3206** [AsahiLinux/docs#41]
I know this isn't an issue per se, but I didn't know where else to ask. macOS Ventura is coming out here soon, but I'm wary about installing it out of fear of breaking my Asahi install. Does anyone know the likelihood of such a thing happening?

**Comment by marcan** [comment]
macOS updates by and large do not affect Asahi Linux by design. There was an exceptional issue due to pre-existing bugs that we noticed when the betas came out, but it's been long fixed.

Just make sure you've updated your packages and you'll be fine.
