### ISSUE TITLE
Having a problem with the instal through terminal on macOS. Some problem with the partition size? 

### ISSUE THREAD

**Issue by ItsBarrett1417** [AsahiLinux/docs#43]
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1440  100  1440    0     0    793      0  0:00:01  0:00:01 --:--:--   797

Bootstrapping installer:
  Checking version...
  Version: v0.4.1
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
/etc/sudoers:15:19: empty netgroup
Dafaults	env_keep += "CHARSET LANG LANGUAGE LC_ALL LC_COLLATE LC_CTYPE"
                  ^
Password:

Welcome to the Asahi Linux installer!

This installer is in an alpha state, and may not work for everyone.
It is intended for developers and early adopters who are comfortable
debugging issues or providing detailed bug reports.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.

By default, this installer will hide certain advanced options that
are only useful for developers. You can enable expert mode to show them.
» Enable expert mode? (y/N): n

Collecting system information...
  Product name: MacBook Air (M1, 2020)
  SoC: Apple M1
  Device class: j313ap
  Product type: MacBookAir10,1
  Board ID: 0x26
  Chip ID: 0x8103
  System firmware: iBoot-7459.141.1
  Boot UUID: 4B1AA46A-D850-4983-9DA9-FADB8F471B5E
  Boot VGID: 4B1AA46A-D850-4983-9DA9-FADB8F471B5E
  Default boot VGID: 4B1AA46A-D850-4983-9DA9-FADB8F471B5E
  Boot mode: macOS
  OS version: 12.6 (21G115)
  SFR version: 21.7.115.0.0,0
  System rOS version: 12.6 (21G115)
  No Fallback rOS
  Login user: bearcampbell

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (994.66 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v12.6 [disk3s3, 4B1AA46A-D850-4983-9DA9-FADB8F471B5E]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v12.6 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s3) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r

We're going to resize this partition:
  APFS [Macintosh HD] (994.66 GB, 6 volumes)
  Total size: 994.66 GB
  Free space: 832.28 GB
  Minimum free space: 38.00 GB
  Minimum total size: 200.38 GB (20.15%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (50%): 800GB

Resizing will free up 194.66 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 194,663,059,456 bytes and targeting a new physical store size of 799,999,524,864 bytes
Determined the minimum size for the targeted physical store of this APFS Container to be 166,698,418,176 bytes
Resizing APFS Container designated by APFS Container Reference disk3
The specific APFS Physical Store being resized is disk0s2
Verifying storage system
Using live mode
Performing fsck_apfs -n -x -l /dev/disk0s2
Checking the container superblock
Checking the space manager
Checking the space manager free queue trees
Checking the object map
Checking the encryption key structures
Checking volume /dev/rdisk3s1
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the document ID tree
Checking the fsroot tree
error: doc-id tree: record exists for doc-id 11889, file-id 105199 but no inode references this doc-id
error: doc-id tree: record exists for doc-id 11963, file-id 5122246 but no inode references this doc-id
Checking the extent ref tree
Checking the file key rolling tree
Verifying volume object map space
The volume /dev/rdisk3s1 was found to be corrupt and needs to be repaired
Checking volume /dev/rdisk3s2
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s2 appears to be OK
Checking volume /dev/rdisk3s3
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking snapshot 1 of 1 (com.apple.os.update-BF1DBCA6141B430194B034207E3FA291F4CA4BF9DB67777796325119C61D343F)
Checking the fsroot tree
Checking the file extent tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s3 appears to be OK
Checking volume /dev/rdisk3s4
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s4 appears to be OK
Checking volume /dev/rdisk3s5
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s5 appears to be OK
Checking volume /dev/rdisk3s6
Checking the APFS volume superblock
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s6 appears to be OK
Verifying allocated space
Performing deferred repairs
error: doc-id tree record exists for doc-id 11889, but no inode references this doc-id
Skipped 2/2 repairs of this type in total
Deferred repairs skipped
The container /dev/disk0s2 could not be verified completely
Storage system check exit code is 8
Error: -69716: Storage system verify or repair failed
Failed to run process: diskutil apfs resizeContainer disk0s2 799999524864
root        : ERROR    Process execution failed
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 852, in <module>
    InstallerMain().main()
  File "/private/tmp/asahi-install/main.py", line 704, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 824, in main_loop
    return self.action_resize(parts_resizable)
  File "/private/tmp/asahi-install/main.py", line 635, in action_resize
    self.dutil.resizeContainer(target.name, val)
  File "/private/tmp/asahi-install/diskutil.py", line 208, in resizeContainer
    self.action("apfs", "resizeContainer", name, size, verbose=2)
  File "/private/tmp/asahi-install/diskutil.py", line 38, in action
    subprocess.run(["diskutil"] + list(args), check=True)
  File "/private/tmp/asahi-install/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['diskutil', 'apfs', 'resizeContainer', 'disk0s2', '799999524864']' returned non-zero exit status 1.
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log`

**Comment by marcan** [comment]
Your macOS filesystem is corrupted (it was already corrupted to begin with, this wasn't caused by the installer). Please run First Aid from Disk Utility in recovery mode and try again.

**Comment by ItsBarrett1417** [comment]
thanks, disk utility did not work (from recovery) so i wiped my mac. it works now
