### ISSUE TITLE
No apt or apt-get command on m1

### ISSUE THREAD

**Issue by ItsBarrett1417** [AsahiLinux/docs#47]

**Comment by Capta1nT0ad** [comment]
`apt` and `apt-get` are only for Debian and Debian derivatives like Ubuntu (and derivatives of Ubuntu). The Asahi Linux reference distribution is based on Arch Linux, so to install a package you would use `pacman -S package-name`. If you would like to install Debian or another distrobution, please remove Asahi Linux from your computer following the cheatsheet at https://github.com/AsahiLinux/docs/wiki/Partitioning-cheatsheet, and install an unofficial version listed at https://github.com/AsahiLinux/docs/wiki/SW%3AAlternative-Distros.

**Comment by ItsBarrett1417** [comment]
thanks
