### ISSUE TITLE
Mac mini with macOS13.2 can‘t connet to Host（ubuntu on vmware workstation on x86 windows 10） in proxy mode using USBA-USBC

### ISSUE THREAD

**Issue by simulink9** [AsahiLinux/docs#51]
Sorry for trouble you，I met one unexpected problem.
I am using a mac mini with macOS13.2, in ITR's terminal
$ kmutil configure-boot -c m1n1.bin --raw --entry-point 2048 --lowest-virtual-address 0 -v <path to your OS volume>
Then i restarted the machine
The machine showed **no payloads find， in proxy mode**（which mode i want）
Now i use a USB-C to USB-A cable, with the C side on the m1n1 target. Host is an ubuntu22 on VMware Workstation on  x86 windows 10.
But nothing happened, i coulden’t find /dev/ttyACM, and no devices change on windows10, too.
May i forget to do something? What should I do next?

**Comment by marcan** [comment]
Did you boot the machine *with* the cable connected? m1n1 does not support hotplugging.

**Comment by simulink9** [comment]
> Did you boot the machine _with_ the cable connected? m1n1 does not support hotplugging.

Very very very thanks for your reply !!!
I have tried cable conneted, but it still not work.
Then I choose macOS12.4 in stub partition, installed proxy mode by the installer, but it is still not work.
The m1n1_proxy mode shows

Running proxy...

I think it is run normally. However, no devices changed on my windows10 computer. 
Then I use my phone to connect the type-c port in mac-mini, this port is powerd and my phone is charging. So, the port is not broken.
What should i do next? My windows10 computer did't have some driver？
Thanks for your reply again!

**Comment by marcan** [comment]
It should work, but I don't think anyone has tried this with a Windows host. We all work using macOS or Linux hosts.

**Comment by simulink9** [comment]
> It should work, but I don't think anyone has tried this with a Windows host. We all work using macOS or Linux hosts.

OK， let me try a Linux host. Thanks!!!

**Comment by simulink9** [comment]
> It should work, but I don't think anyone has tried this with a Windows host. We all work using macOS or Linux host
It couldn't work, too. Maybe I do something wrong, no one has met this problem like me. Thanks for your reply!
