### ISSUE TITLE
Traceback Error from attempting to install to an external drive

### ISSUE THREAD

**Issue by sukadateam** [AsahiLinux/docs#52]
[installer.log](https://github.com/AsahiLinux/docs/files/10388127/installer.log)

Attempting to install Asahi to an external drive, as my Mac doesn't have a lot of storage. 500GB is all it has, and it's full. External thumb drive is 256gb with usb 3.0.

**Comment by marcan** [comment]
01-10 20:44 root         INFO     MSG: Please do not file bugs if things go wrong in expert mode.
     01-10 20:44 root         INFO     MSG: [1;37m»[1;36m Enable expert mode? (y/N): [m
     01-10 20:44 root         INFO     INPUT: 'y'

External installs are not supported.
