### ISSUE TITLE
Open bsd bootable installer fails on loading dmseg. Worked before.

### ISSUE THREAD

**Issue by newusernamed** [AsahiLinux/docs#53]
suspect it came from wiping the whole ssd in recovery mode and creating a new partition and executing macos recovery to reinstall mac os on it affect the boot chain

**Comment by marcan** [comment]
I can't tell what this is about from your description. Can you be more specific, please?

**Comment by marcan** [comment]
If this is OpenBSD 7.2, that has a bug that causes it to hang with current firmware. You need to use OpenBSD-current.
