### ISSUE TITLE
How to setup GNOME on Asahi Linux Minimal

### ISSUE THREAD

**Issue by Siilwyn** [AsahiLinux/docs#56]
Just wanted to share my notes / guide setting up GNOME from zero, in case anybody is searching for this info.
Note I'm opting for wayland options and some things could be done differently, just found these the most straightforward way.

- setup dance
  - login as root with password root
  - `systemctl start iwd`
  - `iwctl`
    - `station wlan0 scan`
    - `station wlan0 connect *network name*`
    - `quit`
  - `ping archlinux.org`
  - `systemctl start dhcpcd`
  - `pacman -Syu`
- `reboot`
- go through setup dance again
- `pacman -S gnome` followed with these non-defaults:
  - `1-60`
  - `pipewire-jack`
  - `wireplumber`
- `pacman -S networkmanager`
- `systemctl enable gdm`
- `shutdown`
- login as alarm user, create new user through gnome settings & logout
- login as new user
- `systemctl enable NetworkManager`
- delete alarm user using gnome settings
- change root password
- lock the root user password with `sudo passwd -l root`
- disable root login with `sudo usermod -s /usr/sbin/nologin root`

**Comment by Soil13** [comment]
Hi guys !  I have just install Fedora Asahi Remix on my Mac , can someone help me to install Gnome 45 desktop please ?
