### ISSUE TITLE
j416sap shows as not supported despite being listed in docs

### ISSUE THREAD

**Issue by oakwizard** [AsahiLinux/docs#57]
As per https://github.com/AsahiLinux/docs/wiki/Devices, j416sap (MacBook Pro (16-inch, M2 Pro, 2023)) should be supported, but when running `curl https://alx.sh | sh` the following message is printed:

```
Collecting system information...
  Product name: MacBook Pro (16-inch, 2023)
  SoC: Apple M2 Pro
  Device class: j416sap
  Product type: Mac14,10
  Board ID: 0x6
  Chip ID: 0x6020
  System firmware: iBoot-8419.80.7
  Boot UUID: E49A64EA-A378-4C50-B6A8-0C95C1780A38
  Boot VGID: E49A64EA-A378-4C50-B6A8-0C95C1780A38
  Default boot VGID: E49A64EA-A378-4C50-B6A8-0C95C1780A38
  Boot mode: macOS
  OS version: 13.2 (22D49)
  SFR version: 22.4.49.0.0,0
  System rOS version: 13.2 (22D49)
  No Fallback rOS
  Login user: redacted

This device is not supported yet!
Please check out the Asahi Linux Blog for updates on device support:
```

**Comment by jannau** [comment]
I've clarified the language on [Devices](https://github.com/AsahiLinux/docs/wiki/Devices). The list should not imply that any devices are already supported. [Feature-Support](https://github.com/AsahiLinux/docs/wiki/Feature-Support) is a better source to check if and how a specific device is already supported.
There will a blog post hen M2 / M2 Pro/Max based Mac minis and Macbook Pros 14"/16" are supported. AFAIK M2 Pro/Max based devices are not yet delivered to any developer. It will take a few weeks until those devices are supported to a similar level as the M1 based devices.
