### ISSUE TITLE
installer won't crop partition

### ISSUE THREAD

**Issue by arch-user-france1** [AsahiLinux/docs#58]
On macos ventura I constantly get:
```
» New size (min): 80%
Size is too small, please enter a value > 245.11 GB (100.00%)
» New size (min): 
```

I have had turned on tmbackups however  after following the linked guide on how to delete tmbackups it still didn't work.
I even restarted the thing.

Have a look:
<img width="1099" alt="grafik" src="https://user-images.githubusercontent.com/72965843/216691657-9562958c-a997-4dfb-959e-2e02a56916fc.png">

<img width="1082" alt="grafik" src="https://user-images.githubusercontent.com/72965843/216691746-78b0fd85-5ee4-484d-81f3-628144bdcec4.png">

<img width="1069" alt="grafik" src="https://user-images.githubusercontent.com/72965843/216691774-8f2b009a-3fd8-4d77-94b2-332941904b8e.png">

<img width="1084" alt="grafik" src="https://user-images.githubusercontent.com/72965843/216691813-b2f6dc3f-a57e-4fc2-8de4-562130f05865.png">

There's definitely free space here so it's either bad documented or an installer problem.

What can be done here?

Sincerely

I have just tried:
```
➜  ~ sudo diskutil apfs resizeContainer disk0s2 240GB
Started APFS operation
Aligning shrink delta to 5,107,195,904 bytes and targeting a new container size of 240,000,000,000 bytes
Determined the minimum size for the APFS Container to be 245,107,195,904 bytes
Error: -69521: Your APFS Container resize request is below the APFS-system-imposed minimal container size (perhaps caused by APFS Snapshot usage by Time Machine)
➜  ~ 
```
However, as I said already, deleting TM Backups didn't seem to work.

**Comment by arch-user-france1** [comment]
Hmm
deleting them one by one didn't work, but this worked instead:
```
sudo tmutil deletelocalsnapshots /
```

I have no clue what happened before.

**Comment by bjoernh** [comment]
For me I had to also checkout my data apfs container for snapshots and find this...
```
sudo diskutil ap listSnapshots /dev/disk3s5
Snapshot for disk3s5 (1 found)
|
+-- 29A36440-8615-4570-8B05-9C3E9FE7D71D
    Name:        com.apple.TimeMachine.2023-07-20-100620.local
    XID:         4414746
    Purgeable:   Yes
    NOTE:        This snapshot limits the minimum size of APFS Container disk3
```
after deleting this apfs snapshot with
```
sudo diskutil ap deleteSnapshot disk3s5 -uuid 29A36440-8615-4570-8B05-9C3E9FE7D71D
Deleting APFS Snapshot 29A36440-8615-4570-8B05-9C3E9FE7D71D "com.apple.TimeMachine.2023-07-20-100620.local" from APFS Volume disk3s5
Started APFS operation
Finished APFS operation
``` Installer can resize my volume :)
