### ISSUE TITLE
SW:Ubuntu Asahi *

### ISSUE THREAD

**Issue by tobhe** [AsahiLinux/docs#60]
Opening an issue here for the lack of a better communication channel. I am wondering if the Asahi wiki is actually the right place for those instructions: [Gambas](https://github.com/AsahiLinux/docs/wiki/SW:Ubuntu-Asahi-Gambas) [Godot](https://github.com/AsahiLinux/docs/wiki/SW:Ubuntu-Asahi-Godot) [Mesa](https://github.com/AsahiLinux/docs/wiki/SW:Ubuntu-Asahi-Mesa) [Qemu](https://github.com/AsahiLinux/docs/wiki/SW:Ubuntu-Asahi-Qemu).

As I understand it, most if not all of the discussed tools should be available in the official repos. There also don't seem to be any Asahi/Apple Silicon specific quirks in those build instructions, so I wonder if the Asahi wiki is the right place to document them. If any of the tools don't work out of the box I think it would be better to file bugs in the Ubuntu or upstream bug trackers (or in [the ubuntu-asahi one](https://github.com/tobhe/ubuntu-asahi/issues) in case of doubt) and try to get them fixed at the source.

I find the [mesa one](https://github.com/AsahiLinux/docs/wiki/SW:Ubuntu-Asahi-Mesa) in particular problematic since it might give users the impression that it is a good idea to replace the packaged and tested mesa with their own git version, which is not something I would recommend for most people.

@xet7 since you authored those pages, what do you think?

**Comment by xet7** [comment]
@tobhe 

You can delete that Mesa page or all of those 4 pages, if you like. I made backups to:

- https://github.com/wekan/wekan/wiki/Gambas
- https://github.com/wekan/wekan/wiki/Godot
- https://github.com/wekan/wekan/wiki/Mesa
- https://github.com/wekan/wekan/wiki/Qemu

**Comment by xet7** [comment]
@tobhe 

Is that mesa-asahi-edge in Ubuntu Asahi yet ?

https://asahilinux.org/2023/03/road-to-vulkan/

**Comment by xet7** [comment]
@tobhe 

Newest mesa with glxgears improved from 60 FPS to 1500 FPS:

https://github.com/wekan/wekan/wiki/Mesa

**Comment by xet7** [comment]
Probably I did something wrong when compiling or testing. Performance did not improve in Godot examples I tried.

**Comment by tobhe** [comment]
hi @xet7, I am still working on the new package updates. I already have a first version working locally so It will probably start rolling out within the next few days.

**Comment by tobhe** [comment]
@xet7 updates are out, also closing this since the problem is resolved
