### ISSUE TITLE
Add Spotify to Broken Software

### ISSUE THREAD

**Issue by benjamingwynn** [AsahiLinux/docs#63]
Spotify does not currently have an Aarch64 build, and as far as I'm aware it doesn't work in the browser due to a lack of widevine.

There is a thread tracking this on Spotify here: https://community.spotify.com/t5/Closed-Ideas/Desktop-ARM-linux-version-of-spotify-app/idi-p/5274705

This should probably be added to the broken software list on the wiki

**Comment by DavidBuchanan314** [comment]
fyi [spotifyd](https://github.com/Spotifyd/spotifyd) works nicely, but you will need to use another device to run the "controlling" session.

If you can make the browser *pretend* to support widevine, perhaps you could use a web session to control a local spotifyd instance.

I have been pondering a solution to the widevine issue at large - Google does not produce aarch64 builds of widevine for linux.

Potential options are:

 - shim the macos aarch64 widevine blobs (tricky, especially without breaking DMCA)
 
 - shim the linux x86_64 widevine blobs running under QEMU/rosetta2 (tedious and fiddly, requiring a cross-arch interposer)

**Comment by DavidBuchanan314** [comment]
I now have spotify working via the web interface, combined with a local spotifyd instance for actual playback:
![image](https://user-images.githubusercontent.com/13520633/223010943-83c27539-c38c-45a8-bf1f-60fe4931a8b5.png)

I wrote this userscript to fake the presence of widevine: https://gist.github.com/DavidBuchanan314/4ba4cf1018c616b33bc2d3c8b68ddb84

Obviously it won't work if you try to play something within the browser, but if you select your spotifyd instance as a playback device first then it'll work.

**Comment by frigaut** [comment]
either that, or you can use a client like spotify-tui, which I am using right now to play music in combination with spotifyd. Works good. Very low cpu usage too :-)

**Comment by DavidBuchanan314** [comment]
I now have widevine + spotify web working on asahi, I'll document how I set it up soon (it's quite a convoluted process...)

**Comment by benjamingwynn** [comment]
@DavidBuchanan314 this is amazing work and I can't wait to try this out! I could foresee myself writing this as an AUR package or something, until official support comes along.

Another idea I had, not sure how feasible it is or whether it would work or not, is to use the patched Rosetta 2 Linux executable with the x86 `spotify` package. I know Spotify just runs a browser underneath, even on desktop, but I'm not sure if that plugs into Widevine and Widevine can't be used with Rosetta, or what the deal is there exactly.

@frigaut 100% a TUI is better than nothing, but I often find myself itching to see some beautiful album art ;)

**Comment by mkurz** [comment]
> ...to use the patched Rosetta 2 Linux executable...

Wait, what? there is a patched Rosetta 2 Linux executable that runs on Asahi's 16kb page size?

**Comment by DavidBuchanan314** [comment]
> @DavidBuchanan314 this is amazing work and I can't wait to try this out! I could foresee myself writing this as an AUR package or something, until official support comes along.
> 
> Another idea I had, not sure how feasible it is or whether it would work or not, is to use the patched Rosetta 2 Linux executable with the x86 `spotify` package. I know Spotify just runs a browser underneath, even on desktop, but I'm not sure if that plugs into Widevine and Widevine can't be used with Rosetta, or what the deal is there exactly.

I'm currently talking to the maintainer of the widevine-aarch64 AUR package about incorporating my script into the package. RE: "official support", that's probably never going to happen. IIUC, the only publicly available widevine builds for Linux arm (armv7 or aarch64) are ones extracted from Chromebooks, which will always require a certain amount of hackery to run on non-chromeos devices.

I might look into making spotify work under rosetta too, although it would probably be a massive pain. I'd need to apply similar 16k alignment patches to the spotify binary, and any other libs it needs to load. Spotify desktop does indeed incorporate widevine, but I think it's only used some of the time (podcast videos?) - Spotify uses their own in-house "DRM" system for normal music playback.

**Comment by marcan** [comment]
Just to go back to the original issue here: "Broken software" is for software that has issues. Software not available for arm64 at all does not qualify, since there is a huge amount of such software.

What we might want is to have a *different* list for popular apps without arm64 versions, and alternatives (like Spotify and Discord), but that's different from "Broken software".

**Comment by benjamingwynn** [comment]
Agreed, if you add a new section to the wiki or something I can change the title of this issue

**Comment by Fuseteam** [comment]
i cannot access the idea linked in the OP, i've submitted a new one here: https://community.spotify.com/t5/Live-Ideas/arm64-support/idi-p/6551110

**Comment by benjamingwynn** [comment]
@Fuseteam it's been over a year, nowadays you can install `widevine-installer` or see https://www.da.vidbuchanan.co.uk/blog/netflix-on-asahi.html for more info

**Comment by mkurz** [comment]
> @Fuseteam it's been over a year, nowadays you can install `widevine-installer` or see https://www.da.vidbuchanan.co.uk/blog/netflix-on-asahi.html for more info

FYI; as of today, the link in this blog to the AUR is broken. It was pushed to https://codeberg.org/mogwai/widevine instead. (They AUR was removed unfortunately, see https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/IAHLWRGRNHHUZRU2LRMX5UTZUNGJBAUO/#5CT5XAQZNIHQYPSRZ6CMDTY67XE3QOU2)

**Comment by Fuseteam** [comment]
@benjamingwynn yeah but there is no build of spotify for arm afaict, hence why i submitted that idea
