### ISSUE TITLE
Night Color Not working

### ISSUE THREAD

**Issue by winthers** [AsahiLinux/docs#67]
As stated in the title, the Night Color is not working, tried the redshift aswell same result. 

im running:
linux-asahi-edge 
mesa-asahi-edge
plasma-wayland-session

**Comment by jannau** [comment]
Support for night color in kwin 5.27.4 or later will come soon, other software adjusting the color temperature will not work unless it uses CTM (color transformation matrix). I'm not aware of any other software supporting this yet.

**Comment by liberodark** [comment]
Hi,

For me is working on last KDE version.

Best Regards

**Comment by lacamar** [comment]
What is needed now for night colour to work on other wayland-based desktop environments?

**Comment by rowanG077** [comment]
Read @jannau comment... It will work if they use CTM (color transformation matrix).

**Comment by rowanG077** [comment]
You'd have to ask the project devs of the project you want it to support. It's not inherently difficult to implement.

**Comment by lacamar** [comment]
Okay, I just created an issue for this on the gammastep gitlab project https://gitlab.com/chinstrap/gammastep/-/issues/54

**Comment by jannau** [comment]
For reference the KDE bug which led to the implementation https://bugs.kde.org/show_bug.cgi?id=455720

**Comment by hedayat** [comment]
There is also an open issue for Gnome (mutter): https://gitlab.gnome.org/GNOME/mutter/-/issues/2318
