### ISSUE TITLE
How to run Linux with keyboard.

### ISSUE THREAD

**Issue by Zzzec** [AsahiLinux/docs#7]
https://github.com/AsahiLinux/docs/wiki/SW%3ALinux#linux-usb-keyboard
This part of doc seems out-of-date.

**Comment by nanays** [comment]
I meet the same question, after boot linux, sceen is stopped in "select a language", but I can not input anything with my usb keyboad. 
   
![image](https://user-images.githubusercontent.com/93510718/139645667-340d81c0-049b-44e0-ad30-12904030282c.png)

 I don‘t know how to get around the problem.  
 linux source code is from  github.com/AsahiLinux/linux and m1n1 macho is  created by "cat build/m1n1.macho ../Image.gz ./build/dtb/t8103-j274.dtb ../initrd.gz > m1n1-payload-init.macho".

**Comment by lgorence** [comment]
I just recently picked up an M1 mini and I had luck with using the latest linux-next tree. USB keyboard, mass storage devices, and even USB hot plug work out of the box. My friend also had the Ethernet port working with a Debian install by adding the linux-firmware package from the non-free apt repo. He mentions that he used `make mod2yesconfig` to switch any possible modules to be built directly into the kernel itself.

**Comment by amworsley** [comment]
Sven just pointed out to me the dtb (device tree) from the linux next tree doesn't have any USB nodes => no USB devices will be found...

I just tried the linux-next next-20211104 kernel and hit the no USB problem and was stuck with USB keyboard not working. 
I switched to my original device tree and low and behold USB keyboard is working.
The USB nodes it had were:

....
                usb@382280000 {
                        compatible = "snps,dwc3";
                        reg = <0x03 0x82280000 0x00 0x100000>;
                        interrupt-parent = <0x03>;
                        interrupts = <0x00 0x309 0x04>;
                        dr_mode = "host";
                        iommus = <0x05 0x00 0x06 0x01>;
....
                usb@502280000 {
                        compatible = "snps,dwc3";
                        reg = <0x05 0x2280000 0x00 0x100000>;
                        interrupt-parent = <0x03>;
                        interrupts = <0x00 0x359 0x04>;
                        dr_mode = "host";
                        iommus = <0x07 0x00 0x08 0x01>;
                };
....

**Comment by amworsley** [comment]
Noticed comment on the IRC #asahi to use https://github.com/mu-one/linux/tree/20211022
github tree which appears to have USB - but nodes are called differently.

Still doesn't have the apple SPI master needed for the M1 builtin keyboard.

**Comment by nanays** [comment]
Thanks very much, now I can use USB keyboad/mouse/storage with an USB HUB C. 
The linux source code is from kernel/git/next/linux-next.git 
and dtb source code is from
https://github.com/AsahiLinux/linux/blob/sven/20210904/arch/arm64/boot/dts/apple/t8103-j274.dts
https://github.com/AsahiLinux/linux/blob/sven/20210904/arch/arm64/boot/dts/apple//t8103.dtsi

**Comment by tom-cai12** [comment]
same problem:  linux USB keyboard does not work for me as well. I am trying to install Linux onto my Macbook air M1.

I followed the instructions at https://github.com/AsahiLinux/docs/wiki/SW%3ALinux 
the Asahi dart/dev kernel  was cloned from https://github.com/AsahiLinux/linux.git

I am new in this area, is there an easy way to get around with it? detailed steps are welcome.
Thanks.

**Comment by tom-cai12** [comment]
Hi Nanays,
I can't find clone site for the linux source code you mentioned (kernel/git/next/linux-next.git). what is the Extract linux via git command you used? 
Thanks
Tom

**Comment by nanays** [comment]
The linux-next that  i used is next-20211104 kernel and you can get it with command: "git clone https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git" and 
the lasted commit is 8a796a1dfca2780321755033a74bca2bbe651680.

**Comment by tom-cai12** [comment]
Thanks Nanays! 
With the linux source code from kernel/git/next/linux-next.git, I was able to bring up the linux onto my Macbook Air M1 and was able to use HP keyboard via USB to send commands. But with this Linux code,  it seems that I can't do cpu core controlled tasks (eg. to force big/little core to run), neither to force cpu to run at different cpu frequency.  I guess that will have to wait until next Asahi linux release?

**Comment by zimsneexh** [comment]
> Thanks Nanays! With the linux source code from kernel/git/next/linux-next.git, I was able to bring up the linux onto my Macbook Air M1 and was able to use HP keyboard via USB to send commands. But with this Linux code, it seems that I can't do cpu core controlled tasks (eg. to force big/little core to run), neither to force cpu to run at different cpu frequency. I guess that will have to wait until next Asahi linux release?

Hey!
Which device tree did you use to get this to work?

Thanks.

**Comment by marcan** [comment]
Folks, this repo is for documentation, not troubleshooting kernels. Thiere is no Asahi Linux release yet; we're still working on finishing and upstreaming drivers. You're welcome to figure things out yourselves if you want to test bleeding edge kernels, but let's not clutter up the issue tracker with this.

If you would like to test what is currently the "canonical" WIP kernel with some patches not yet upstreamed, please try this branch:

https://github.com/asahilinux/linux/tree/asahi
