### ISSUE TITLE
How to enable Full Security mode after uninstalling Asahi?

### ISSUE THREAD

**Issue by corv89** [AsahiLinux/docs#71]
What do I have to consider and how do I re-enable Full Security mode (or rather the original system configuration in terms of security settings) after uninstalling Asahi Linux?

It's been a while since I installed Asahi and I simply can't remember what the installer changed or prompted me to change, sorry!

(I've actually not uninstalled and am happily following along development progress but would like to know for completeness sake)

**Comment by heisenbirb** [comment]
First, Reboot your mac into recovery mode by holding the shutdown button when booting. Log in, open the terminal from the utilites menu, run the command 
`csrutil enable`
then restart your computer.

**Comment by corv89** [comment]
Thanks for the quick reply.

I did search extensively before posting, and while I might have missed something it seems this is undocumented?

**Comment by discentem** [comment]
I didn't think Asahi disable SIP. Does it?

**Comment by jannau** [comment]
There is nothing to change after removing the partitions created by the installer. The security settings are per installed OS and not system wide. The installer does not modify any macOS installation.

**Comment by tjex** [comment]
> I didn't think Asahi disable SIP. Does it?

yes, that is what `csrutil` is for. https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection
