### ISSUE TITLE
How to prevent macOS to automount Asahi Linux's "stub" APFS volumes?

### ISSUE THREAD

**Issue by sisungo** [AsahiLinux/docs#72]
Installing Asahi Linux creates a stub macOS-like installation, an APFS partition with volumes like `Asahi Linux` and `Asahi Linux - Data`, which is automatically mounted by macOS on boot. How to prevent the partition to be mounted automatically by macOS?

**Comment by CodeRuner5235** [comment]
https://discussions.apple.com/docs/DOC-7942

Give this a shot
