### ISSUE TITLE
Chromium does not launch on latest asahi

### ISSUE THREAD

**Issue by DaveFlashNL** [AsahiLinux/docs#75]
So the Google Chromium browser is non operable in current asahi, is there any fix for that?

**Comment by DavidBuchanan314** [comment]
Assuming you're talking about the libre2 version mismatch, that's an Arch Linux Arm packaging issue, and not an asahi issue. You can work around it by downgrading libre2.

If you trust me, which I don't recommend, the previous version is available here:

[re2-1:20230301-1-aarch64.pkg.tar.xz.zip](https://github.com/AsahiLinux/docs/files/12552042/re2-1.20230301-1-aarch64.pkg.tar.xz.zip)

**Comment by jannau** [comment]
This arch linux arm forum [topic](https://archlinuxarm.org/forum/viewtopic.php?f=8&t=15662) lists archive mirrors which should have previous builds of the re2 package.
The older versions might be still in `/var/cache/pacman/pkg/` on the system if the package cache is not pruned.
