### ISSUE TITLE
Current list of what doesn’t work

### ISSUE THREAD

**Issue by danielktdoranie** [AsahiLinux/docs#80]
Hi! First off thanks to everyone in the community who is doing the hard work of making this OS reality. 

Request: could someone in the know make a list of what hardware is currently not working in Asahi Linux? The last update that I can find is from 2022 here: https://asahilinux.org/2022/03/asahi-linux-alpha-release/ (under the “What Doesn’t” section).

I am really curious if any of the list items under “What Doesn’t” are now working. 

Thank you!

**Comment by carlonluca** [comment]
https://github.com/AsahiLinux/docs/wiki/Feature-Support?

**Comment by jonathancross** [comment]
https://github.com/AsahiLinux/docs/blob/main/docs/platform/feature-support/overview.md
