### ISSUE TITLE
Document expert mode

### ISSUE THREAD

**Issue by NAThompson** [AsahiLinux/docs#82]
The blog post announcing M2 support indicates that the user must enable expert mode in order to install. However, the precise means of entering expert mode is not documented.

By some sleuthing around, I was able to succeed with:

```bash
export EXPERT=1
curl https://alx.sh | sh
```

However, I found this option by searching around the git repo.

(Sincerest apologies for not just submitting a fix-I couldn't figure out where it should go!)

**Comment by DavidBuchanan314** [comment]
I might be wrong, but I suspect expert mode is deliberately obscured so that non-experts don't end up using it

**Comment by jannau** [comment]
Yes, expert mode is is not documented for a reason. It was initially an option in the installer but too many people used that and ended up selecting unsupported options proving that they are no experts.
The outdated information from the M2 blog post should be redacted.

**Comment by marcan** [comment]
This is undocumented by design. When it was documented, too many people decided they were "experts".

**Comment by LouieMjr** [comment]
> You absolutely do not need expert mode to install on M2. That was only required for like the first month after the machines came out.

But you do need for M2 Pro for now?
