### ISSUE TITLE
Installer crashing at stage 2; Local policy update.

### ISSUE THREAD

**Issue by slimjimsoftware** [AsahiLinux/docs#84]
First off, I've installed and re-installed Asahi more times than I can remember on this machine, I'm not sure if that has anything to do with that and / or if I've munted something permanently but the point is, please don't tell me I'm 'doing it wrong', I follow the instructions to a tee every time.

After installing fedora and following a Sonoma update, I wanted to return to Arch because even though it's a bit flaky now and then some software I use daily has been fixed in the AUR but is still broken in fedora 39 and I didn't want to faff around rebuilding RPMs from source and applying custom patches. So, I did what I've done at least a dozen times before and used the wipe-linux script to blow away the partitions, rebooted back into macOS just to be safe, then ran the installer from https://alx.sh again - this time however, when I got to the stage 2 part, the system crashed at "Local policy update is in progress"...  and went into a boot-loop.

I've tried again, multiple times, but now it just will not install no matter what I do. It's always the same thing, it gets to stage 2, I enter my credentials and after anywhere between about 5 and 45 seconds, the entire machine crashes, then it goes into a boot loop.

You can see an example of this in the following video, it happens at about 20 seconds in to the video, which is about 45 seconds after hitting enter. The screen goes black and the system goes into a boot-loop.  
https://drive.google.com/file/d/1E_rQM_22fj19AfPoTmvcgNSk2Nn5uI3r/view?usp=drive_link

**Comment by jannau** [comment]
> First off, I've installed and re-installed Asahi more times than I can remember on this machine, I'm not sure if that has anything to do with that

yes, it probably has. Each install leaves stale boot policies behind and bputil can not handle more than around 30 or so. See https://github.com/AsahiLinux/asahi-installer/blob/main/tools/cleanbp.sh (https://alx.sh/cleanbp forwards to it) for a script cleaning them up.

**Comment by slimjimsoftware** [comment]
> > First off, I've installed and re-installed Asahi more times than I can remember on this machine, I'm not sure if that has anything to do with that
> 
> yes, it probably has. Each install leaves stale boot policies behind and bputil can not handle more than around 30 or so. See https://github.com/AsahiLinux/asahi-installer/blob/main/tools/cleanbp.sh (https://alx.sh/cleanbp forwards to it) for a script cleaning them up.

Aha! That fixed it! Thanks a lot.
