### ISSUE TITLE
Boot Failure

### ISSUE THREAD

**Issue by MarcusJohnson91** [AsahiLinux/docs#87]
Hi, I just read your Sonoma Boot Failure wiki article, and I think this happened to my 2014 Intel Mac with the 12.6.5 update, while I had Ubuntu installed on a second partition.

intel Macs do not have DFU mode, is there anything that can be done for Intel?

**Comment by marcan** [comment]
This issue fundamentally only affects Apple Silicon Macs, and then only 14" and 16" models. Your issue is completely unrelated. Sorry, we can't help you here.
