### ISSUE TITLE
bputil causes restart

### ISSUE THREAD

**Issue by BokBoy** [AsahiLinux/docs#89]
~~Hey all,
I'm up to the bless part of the installer, where it panics and reboots my system. 
Its happened with all of the asahi installers (I'm talking other distros, including fedora and ubuntu) and it always restarts. I submitted the report to apple so I'm waiting.
Thanks...~~

Its now getting stuck at bputil.

System Info (edited because forgot)
MacBook Air M2 with 8 core CPU and GPU. 
8GB ram, normally 1GB is dedicated to the GPU.
Mac14,2 (13")

**Comment by BokBoy** [comment]
Also, if this isnt the place, sorry, I'm new here.

**Comment by rowanG077** [comment]
This is indeed not the place. This is specific for nixos. I would advise you to report this on the fedora asahi forum. Fedora is essentially the "main" distro for Asahi. The original develops are active there. https://discussion.fedoraproject.org/c/neighbors/asahi/92

**Comment by BokBoy** [comment]
@rowanG077 This isn't to do with Nixos
Im installing Asahi Minimal

**Comment by rowanG077** [comment]
Ah sorry you are right I got the repos confused. Sorry.

**Comment by BokBoy** [comment]
Its fine, anything else??

**Comment by BokBoy** [comment]
Oh wait, should I add that this isn't the first time, its like my tenth?? 
I'm running 14.2 Beta too??

**Comment by BokBoy** [comment]
Update, Bless managed to bless the disk, its now stuck after the first part in recovery where it panics.

**Comment by BokBoy** [comment]
Hello??

**Comment by BokBoy** [comment]
Ok I tried Fedora 39 Minimal latest and it still doesn't bputil
pls help

**Comment by BokBoy** [comment]
Reset my pc and fixed it, I don't know cause tho
